name: Fetch data
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: false
        default: 'JavaGT'
        type: string
jobs:
  Update-Youtube-Data:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "installing npm modules"
      - name: Install modules
        run: |
          npm install
      - name: Run nodejs code
        run: |
          node ${{ github.workspace }}/main.mjs
      - name: Commit report
        run: |
          git config --global user.name 'GITHUB WORKFLOW'
          git config --global user.email 'JavaGT@users.noreply.github.com'
          git add -A
          git commit -am "Updated youtube files"
          git push
      - run: echo "ğŸ This job's status is ${{ job.status }}."
